### ISSUE TITLE
TE: Windows 7 x86 crashes with exception e0434352

### ISSUE THREAD

**Issue by ABelliqueux** [MontyTRC89/Tomb-Editor#715]
## Description

Trying to launch "Tomb Editor" or "WadTool" results in an appcrash with exception code **e0434352**.
It looks like the issue is the same for both programs ( see logs ).

"Soundtool" and "TombIDE" launch fine.

Fwiw, I have no trouble running the original TR games and TRLE ("room editor").

## System specs

OS: Windows 7 Pro 32bits (6.1, version  7601) (Fresh install, Up to date, French locale)
SW: ~~DX 9.0c~~ DX11, nvidia driver 391.35
Installed .NET version : windowsdesktop-runtime-6.0.21-win-x86.exe

HW: Intel i3, 6GB ram, Nvidia Geforce 620GT 1GB, 500GB HDD

## Error Logs 
```
Signature du problème :
  Nom d'événement de problème:	APPCRASH
  Nom de l'application:	TombEditor.exe
  Version de l'application:	1.6.8.0
  Horodatage de l'application:	6331e747
  Nom du module par défaut:	KERNELBASE.dll
  Version du module par défaut:	6.1.7601.23403
  Horodateur du module par défaut:	56f583e9
  Code de l'exception:	e0434352
  Décalage de l'exception:	0000845d
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	0a9e
  Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
  Information supplémentaire n° 3:	0a9e
  Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789

Signature du problème :
  Nom d'événement de problème:	APPCRASH
  Nom de l'application:	WadTool.exe
  Version de l'application:	1.6.8.0
  Horodatage de l'application:	6331e747
  Nom du module par défaut:	KERNELBASE.dll
  Version du module par défaut:	6.1.7601.23403
  Horodateur du module par défaut:	56f583e9
  Code de l'exception:	e0434352
  Décalage de l'exception:	0000845d
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	0a9e
  Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
  Information supplémentaire n° 3:	0a9e
  Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789
```

Please let me know if I can provide more relevant infos to pinpoint the issue.

**Comment by Lwmte** [comment]
Hi. You need to provide not only system logs, but also TombEditorLog.txt and WadToolLog.txt from the application folder.

**Comment by ABelliqueux** [comment]
Hi, 
Thanks for your reply, I did not know these logs existed. 

As for your questions :  

- I do have .NET 6.0.21 x86 installed (windowsdesktop-runtime-6.0.21-win-x86.exe)
- I have installed the x86 version of TombEditor.


Here are the logs :

**TombEditorLog.txt** :  

```
[13:00:33.510  INFO] TombLib.Utils.Logging | Tomb Editor version 1.6.8 is starting | 
[13:00:33.573  INFO] TombLib.Utils.Logging | Framework version: 6.0 | 
[13:00:33.573  INFO] TombLib.Utils.Logging | TombLib Git Revision: <Information missing> | 
[13:00:34.634  INFO] TombLib.LevelData.Level | Creating new empty level | 
[13:00:35.273  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Dx11 rendering device creating. | 
[13:00:35.336  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Creating D3D device: NVIDIA GeForce GT 620, 969 MB GPU RAM. | 
[13:00:35.663  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Dx11 rendering device created. | 
[13:00:36.178 FATAL] TombLib.Utils.Logging | Unhandled exception | System.TypeInitializationException
The type initializer for 'TombLib.Graphics.DeviceManager' threw an exception.
   at TombEditor.Editor..ctor(SynchronizationContext synchronizationContext, Configuration configuration, Level level)
   at TombEditor.Editor..ctor(SynchronizationContext synchronizationContext, Configuration configuration)
   at TombEditor.Program.Main(String[] args)


System.BadImageFormatException
Tentative de chargement d’un programme de format incorrect. (0x8007000B)
   at SharpDX.D3DCompiler.D3D.D3DPreprocess_(Void* arg0, Void* arg1, Void* arg2, Void* arg3, Void* arg4, Void* arg5, Void* arg6)
   at SharpDX.D3DCompiler.D3D.Preprocess(IntPtr srcDataRef, PointerSize srcDataSize, String sourceNameRef, ShaderMacro[] definesRef, IntPtr includeRef, Blob& codeTextOut, Blob& errorMsgsOut)
   at SharpDX.D3DCompiler.ShaderBytecode.Preprocess(IntPtr shaderSourcePtr, Int32 shaderSourceLength, ShaderMacro[] defines, Include include, String& compilationErrors, String sourceFileName)
   at SharpDX.D3DCompiler.ShaderBytecode.Preprocess(String shaderSource, ShaderMacro[] defines, Include include, String& compilationErrors, String sourceFileName)
   at SharpDX.Toolkit.Graphics.EffectParser.Parse(String input, String fileName)
   at SharpDX.Toolkit.Graphics.EffectCompiler.InternalCompile(String sourceCode, String fileName)
   at TombLib.Graphics.DeviceManager..ctor()
   at TombLib.Graphics.DeviceManager..cctor()
[13:00:55.288  INFO] TombLib.Utils.Logging | Tomb Editor has exited cleanly. | 
```
**WadToolLog.txt** :  
  
```
[12:16:31.585  INFO] TombLib.Utils.Logging | WadTool version 1.6.8 is starting | 
[12:16:31.616  INFO] TombLib.Utils.Logging | Framework version: 6.0 | 
[12:16:31.616  INFO] TombLib.Utils.Logging | TombLib Git Revision: <Information missing> | 
[12:16:31.491  INFO] TombLib.ConfigurationBase | Unable to load configuration from "C:\Tomb Editor\Configs\WadToolConfiguration.xml" | System.IO.FileNotFoundException
File not found
[12:16:32.069  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Dx11 rendering device creating. | 
[12:16:32.069  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Creating D3D device: NVIDIA GeForce GT 620, 969 MB GPU RAM. | 
[12:16:32.147  INFO] TombLib.Rendering.DirectX11.Dx11RenderingDevice | Dx11 rendering device created. | 
[12:16:32.381 FATAL] TombLib.Utils.Logging | Unhandled exception | System.TypeInitializationException
The type initializer for 'TombLib.Graphics.DeviceManager' threw an exception.
   at WadTool.FormMain..ctor(WadToolClass tool)
   at WadTool.Program.Main(String[] args)


System.BadImageFormatException
Tentative de chargement d’un programme de format incorrect. (0x8007000B)
   at SharpDX.D3DCompiler.D3D.D3DPreprocess_(Void* arg0, Void* arg1, Void* arg2, Void* arg3, Void* arg4, Void* arg5, Void* arg6)
   at SharpDX.D3DCompiler.D3D.Preprocess(IntPtr srcDataRef, PointerSize srcDataSize, String sourceNameRef, ShaderMacro[] definesRef, IntPtr includeRef, Blob& codeTextOut, Blob& errorMsgsOut)
   at SharpDX.D3DCompiler.ShaderBytecode.Preprocess(IntPtr shaderSourcePtr, Int32 shaderSourceLength, ShaderMacro[] defines, Include include, String& compilationErrors, String sourceFileName)
   at SharpDX.D3DCompiler.ShaderBytecode.Preprocess(String shaderSource, ShaderMacro[] defines, Include include, String& compilationErrors, String sourceFileName)
   at SharpDX.Toolkit.Graphics.EffectParser.Parse(String input, String fileName)
   at SharpDX.Toolkit.Graphics.EffectCompiler.InternalCompile(String sourceCode, String fileName)
   at TombLib.Graphics.DeviceManager..ctor()
   at TombLib.Graphics.DeviceManager..cctor()
[12:17:39.383  INFO] TombLib.Utils.Logging | WadTool has exited cleanly. | 

```

What is strange is the mention of a DX11 device, whereas I only have DX9 installed, as I believe it's the latest version available for windows 7 (?).

Thanks for your time !

**Comment by Lwmte** [comment]
It looks like error 0x8007000B indicates a mix of 32-bit and 64-bit libraries. 32-bit builds weren't tested for a while, so maybe they got broken. Sadly I can't test it for you right away, but I will ask in dev chat if someone with 32-bit machine can test too.

**Comment by ABelliqueux** [comment]
Just to be sure I uninstalled/reinstalled TombEditor, making sure to use the x86 installer, and still have the same issue. Thanks again for your time.

**Comment by Nickelony** [comment]
I'm afraid supporting 32-bit systems isn't our priority. Many programs stopped shipping x86 installers since even back in 2012 (Vegas Pro for example, 11.0 was the last version to support 32-bit systems).

The chances of us looking into this are slim, especially since we'd need a virtual machine setup to do all the testing, but maybe someone will find some spare time for this in the future, who knows. 🤷

**Comment by Nickelony** [comment]
Starting **TE 1.8**, which is the next update after the upcoming 1.7.2 release, the TE suite will be moved onto **.NET 8**, therefore officially dropping Windows 7 and 32-bit system support entirely.
Sorry, but because of this, we won't be looking into this issue anymore. 😞
