### ISSUE TITLE
TE - Sound sample path delete - System.IndexOutOfRangeException: Index 16 does not have a value.

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#887]
I had imported an old TRLE project, then converted it to TEN.
When I tried to delete the sound sample path (to add a new one), this message appeared.
Once all the errors were gone, it worked.

```
---------------------------
DataGridView Default Error Dialog
---------------------------
The following exception occurred in the DataGridView:

System.IndexOutOfRangeException: Index 16 does not have a value.
   at System.Windows.Forms.CurrencyManager.get_Item(Int32 index)
   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.GetError(Int32 rowIndex)

To replace this default dialog please handle the DataError event.
---------------------------
OK   
---------------------------
```

**Comment by Lwmte** [comment]
Please provide your TRLE project to reproduce the issue, and also more detailed information which sound sample path you were trying to delete.

**Comment by illyaine** [comment]
Again, sorry for the late reply.
I'll have to see if I can remember what I did here and how I did it.
I will of course provide more information in the future, sorry.
