### ISSUE TITLE
WT - System.ArgumentOutOfRangeException: Value of '800206.5' is not valid for 'Value'.

### ISSUE THREAD

**Issue by illyaine** [MontyTRC89/Tomb-Editor#888]
I opened a Lara in .wad format and just let the animations play.

`Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '800206.5' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'. (Parameter 'value')
Actual value was 800206.5.
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at WadTool.FormAnimationEditor.SelectAnimation(AnimationNode node)
   at WadTool.FormAnimationEditor.lstAnimations_SelectedIndicesChanged(Object sender, EventArgs e)
   at DarkUI.Controls.DarkListView.SelectItem(Int32 index)
   at DarkUI.Controls.DarkListView.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.CoreLib.dll
----------------------------------------
WadTool
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/WadTool.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.1032
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/NLog.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/netstandard.dll
----------------------------------------
TombLib
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/TombLib.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Numerics.Vectors.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Drawing.Primitives.dll
----------------------------------------
DarkUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/DarkUI.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1322.60101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1322.60101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.InteropServices.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Specialized.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.Encoding.CodePages.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1322.58009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Drawing.Common.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.Thread.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Xml.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Xml.XmlSerializer.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.RegularExpressions.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ObjectModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Emit.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Xml.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Primitives.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Linq.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Net.Primitives.dll
----------------------------------------
System.Net.Mail
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Net.Mail.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Net.Sockets.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Linq.Expressions.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Uri.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Console.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.StackTrace.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/Microsoft.Win32.Registry.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/Microsoft.Win32.Primitives.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1322.60101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/Accessibility.dll
----------------------------------------
TombLib.Forms
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/TombLib.Forms.dll
----------------------------------------
TombLib.Rendering
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/TombLib.Rendering.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1322.58009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Concurrent.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1322.58009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1322.60101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Drawing.dll
----------------------------------------
SharpDX.Toolkit
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.Toolkit.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/mscorlib.dll
----------------------------------------
SharpDX
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.dll
----------------------------------------
SharpDX.Toolkit.Compiler
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.Toolkit.Compiler.dll
----------------------------------------
SharpDX.Toolkit.Graphics
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.Toolkit.Graphics.dll
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.Direct3D11.dll
----------------------------------------
SharpDX.DXGI
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.DXGI.dll
----------------------------------------
Pfim
    Assembly Version: 0.10.3.0
    Win32 Version: 0.10.3
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/Pfim.dll
----------------------------------------
bzPSD
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/bzPSD.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.dll
----------------------------------------
SharpDX.D3DCompiler
    Assembly Version: 2.4.2.0
    Win32 Version: 2.4.2
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/SharpDX.D3DCompiler.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1322.58009
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Net.WebClient.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Serialization.Formatters.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Xml.dll
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.Tasks.Parallel.dll
----------------------------------------
CH.SipHash
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///E:/TRLE/IONOS%20HiDrive/TRLE/TOMB%20EDITOR/illyaine/CH.SipHash.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.Tracing.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.ThreadPool.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Immutable.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.

`

**Comment by Lwmte** [comment]
Which animations did you play? Which wad were you using?

**Comment by illyaine** [comment]
Sorry for the late reply.
Unfortunately, I had a death in my private life and was very busy.

Animation 459, for example, would be
[Uploading WADFile.zip…]()
